<!-- PRODUTOS MOVIDO PARA CONTEUDO -->
<div class="product-list">
        <h1><span>PRODUTOS</span></h1>
        <div class="scrolling-container">
            <div class="product-card">
            <p><b>CAFÉ TENTAÇÃO 50ML</b></p>
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVqikJLcnpZtDIOc7k_BDXhWnSdIjoZ1p7zBlGuaueWQWvboLPgZmfEFuTlkjSaiNEIqM&usqp=CAU" alt="CAFÉ TENTAÇÃO">
                <p><b> 2 Xícaras R$:20,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CAFÉ CHARMOSO 50ML</b></p>
                <img src="https://i0.wp.com/blog.cicloorganico.com.br/wp-content/uploads/2023/06/cafe-2.jpg?fit=900%2C506&ssl=1" alt="CAFÉ CHARMOSO">
                <p><b> 2 Xícaras R$:15,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CAFÉ ÊXTASE 50ML</b></p>
                <img src="https://www.unimed.coop.br/portalunimed/cartilhas/cafe/images/cafe03.jpg" alt="CAFÉ ÊXTASE">
                <p><b>2 Xícaras R$:10,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CAFÉ DELICIA DO CAFETÃO 50ML</b></p>
                <img src="https://static1.minhavida.com.br/ingredients/99/bf/be/fd/cafe-e-graos-de-cafe-amp_hero-1.jpg" alt="CAFÉ DO CAFETÃO">
                <p><b>2 Xícaras R$:30,00</b></p>
            </div>
            <div class="product-card">
            <p><b>BOLO VULCÃO</b></p>
                <img src="https://d1uz88p17r663j.cloudfront.net/original/8fee36bf950557ff9f896b9104f36907_bolo-vulcao-brigadeiro-receitas-nestle.jpg" alt="BOLO VULCÃO">
                <p><b>2 FATIAS R$:25,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CROISSANT</b></p>
                <img src="https://s2.glbimg.com/CjCye7ok2_y4ZMopRQwGcbZ3aio=/e.glbimg.com/og/ed/f/original/2021/10/08/croissant-frances-1-840x480.jpeg" alt="BOLO VULCÃO">
                <p><b>2 R$:20,00</b></p>
            </div>
        </div>
    </div>


<!-- cardápio com a classe section -->
<div class="section">
    <h1><span>CARDÁPIO</span></h1>
    <table>
                <tr>
                    <th>DIA</th>
                    <th>SEG</th>
                    <th>TER</th>
                    <th>QUA</th>
                    <th>QUI</th>
                    <th>SEX</th>
                    
                </tr>
                <tr>
                    <td>08-8:30</td>
                    <td class="selected">Café Tentação</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Café Tentação</td>
                    <td></td>
                </tr>
                <tr>
                    <td>09-10</td>
                    <td></td>
                    <td class="selected">Delícia do Cafetão</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Delícia do Cafetão</td>
                </tr>
                <tr>
                    <td>13-13:30</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Café Êxtase</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>15:45-16</td>
                    <td></td>
                    <td class="selected">Café Tentação</td>
                    <td></td>
                    <td class="selected">Café Êxtase</td>
                    <td></td>
                </tr>
                <tr>
                    <td>16-17:15</td>
                    <td class="selected">Café Charmoso</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="selected">Café Charmoso</td>
                </tr>
            </table>
</div>

<div class="section">
    <h1><span>MAIS PEDIDOS</span></h1>
    <ul>
                <li>Délicia do Cafetão <br />
                    <progress min="0" max="100" value="100"></progress>
                </li>
                 <li>Café Tentação <br />
                    <progress min="0" max="100" value="100"></progress>
                </li>
                <li>Café Charmoso <br />
                    <progress min="0" max="100" value="80"></progress>
                </li>
                <li>Café Êxtase <br />
                    <progress min="0" max="100" value="10"></progress>
                </li>
            </ul>
</div>

<!-- fale conosco -->
<div class="section" id="fale_conosco">
            <h1><span>FALE CONOSCO</span></h1>
            <form>
                <input name="name" placeholder="NOME" type="text" required /><br/>
                <input name="email" placeholder="EMAIL" type="email" required /><br/>
                <textarea name="messagem" placeholder="MENSAGEM" required ></textarea>
                <input type="submit" value="ENVIAR" class="submit"
                />
            </form>
        </div>