<!-- About Me section start -->
<div class="section">
    <h1><span>About Me</span></h1>
       <p> 
          Hey! I'm <strong>Thiago</strong>. Coding has changed my world. It's not just about apps. Learning to code gave me <i>problem-solving skills</i> and a way to communicate with others on a technical level. I can also develop websites and use my coding skills to get a better job. And I learned it all at <strong>SoloLearn</strong> where they build your self-esteem and keep you motivated. Join me in this rewarding journey. You'll have fun, get help, and learn along the way!
       </p>
</div>

<!-- My Schedule section start -->
<div class="section">
    <h1><span>My Coding Schedule</span></h1>
    <table>
                <tr>
                    <th>Day</th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thu</th>
                    <th>Fri</th>
                    
                </tr>
                <tr>
                    <td>8-8:30</td>
                    <td class="selected">Learn</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>9-10</td>
                    <td></td>
                    <td class="selected">Practice</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1-1:30</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Play</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>3:45-5</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="selected">Code</td>
                    <td></td>
                </tr>
                <tr>
                    <td>6-6:15</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="selected">Discuss</td>
                </tr>
            </table>
</div>

<!-- My Skills section start -->
<div class="section">
    <h1><span>My Skills</span></h1>
    <ul>
                <li>HTML <br />
                    <progress min="0" max="100" value="100"></progress>
                </li>
                 <li>CSS <br />
                    <progress min="0" max="100" value="100"></progress>
                </li>
                <li>JavaScript <br />
                    <progress min="0" max="100" value="80"></progress>
                </li>
                <li>PHP <br />
                    <progress min="0" max="100" value="10"></progress>
                </li>
            </ul>
</div>