<!-- About Me section start -->
<div class="section">
    <h1><span>O CAFETÃO</span></h1>
       <p> 
       <!-- CONTEUDINHO -->  
       </p>
</div>

<!-- My Schedule section start -->
<div class="section">
    <h1><span>CARDÁPIO</span></h1>
    <table>
                <tr>
                    <th>DIA</th>
                    <th>SEG</th>
                    <th>TER</th>
                    <th>QUA</th>
                    <th>QUI</th>
                    <th>SEX</th>
                    
                </tr>
                <tr>
                    <td>08-8:30</td>
                    <td class="selected">Café Tentação</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Café Tentação</td>
                    <td></td>
                </tr>
                <tr>
                    <td>09-10</td>
                    <td></td>
                    <td class="selected">Delícia do Cafetão</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Delícia do Cafetão</td>
                </tr>
                <tr>
                    <td>13-13:30</td>
                    <td></td>
                    <td></td>
                    <td class="selected">Café Êxtase</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>15:45-16</td>
                    <td></td>
                    <td class="selected">Café Tentação</td>
                    <td></td>
                    <td class="selected">Café Êxtase</td>
                    <td></td>
                </tr>
                <tr>
                    <td>16-17:15</td>
                    <td class="selected">Café Charmoso</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="selected">Café Charmoso</td>
                </tr>
            </table>
</div>

<div class="section">
    <h1><span>MAIS PEDIDOS</span></h1>
    <ul>
                <li>Délicia do Cafetão <br />
                    <progress min="0" max="100" value="100"></progress>
                </li>
                 <li>Café Tentação <br />
                    <progress min="0" max="100" value="100"></progress>
                </li>
                <li>Café Charmoso <br />
                    <progress min="0" max="100" value="80"></progress>
                </li>
                <li>Café Êxtase <br />
                    <progress min="0" max="100" value="10"></progress>
                </li>
            </ul>
</div>