<!-- Media section start -->
<div class="section">
            <h1><span>FALE CONOSCO</span></h1>
            <form>
                <input name="name" placeholder="Name" type="text" required /><br/>
                <input name="email" placeholder="Email" type="email" required /><br/>
                <textarea name="messagem" placeholder="Messagem" required ></textarea>
                <input type="submit" value="ENVIAR" class="submit"
                />
            </form>
        </div>