<!-- form com o class section -->
<div class="section">
            <h1><span>FALE CONOSCO</span></h1>
            <form>
                <input name="name" placeholder="NOME" type="text" required /><br/>
                <input name="email" placeholder="EMAIL" type="email" required /><br/>
                <textarea name="messagem" placeholder="MENSAGEM" required ></textarea>
                <input type="submit" value="ENVIAR" class="submit"
                />
            </form>
        </div>