<!-- menu 
ADICIONAR BOTÃO DE CAIXA E SOMAR OS PRODUTOS TUDO COM PHP
E AJUSTAR AS CLASSE DO CSS
-->
<div class="product-list">
        <h1><span>PRODUTOS</span></h1>
        <div class="scrolling-container">
            <div class="product-card">
            <p><b>CAFÉ TENTAÇÃO 50ML</b></p>
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVqikJLcnpZtDIOc7k_BDXhWnSdIjoZ1p7zBlGuaueWQWvboLPgZmfEFuTlkjSaiNEIqM&usqp=CAU" alt="CAFÉ TENTAÇÃO">
                <p><b> 2 Xícaras R$:20,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CAFÉ CHARMOSO 50ML</b></p>
                <img src="https://i0.wp.com/blog.cicloorganico.com.br/wp-content/uploads/2023/06/cafe-2.jpg?fit=900%2C506&ssl=1" alt="CAFÉ CHARMOSO">
                <p><b> 2 Xícaras R$:15,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CAFÉ ÊXTASE 50ML</b></p>
                <img src="https://www.unimed.coop.br/portalunimed/cartilhas/cafe/images/cafe03.jpg" alt="CAFÉ ÊXTASE">
                <p><b>2 Xícaras R$:10,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CAFÉ DELICIA DO CAFETÃO 50ML</b></p>
                <img src="https://static1.minhavida.com.br/ingredients/99/bf/be/fd/cafe-e-graos-de-cafe-amp_hero-1.jpg" alt="CAFÉ DO CAFETÃO">
                <p><b>2 Xícaras R$:30,00</b></p>
            </div>
            <div class="product-card">
            <p><b>BOLO VULCÃO</b></p>
                <img src="https://d1uz88p17r663j.cloudfront.net/original/8fee36bf950557ff9f896b9104f36907_bolo-vulcao-brigadeiro-receitas-nestle.jpg" alt="BOLO VULCÃO">
                <p><b>2 FATIAS R$:25,00</b></p>
            </div>
            <div class="product-card">
            <p><b>CROISSANT</b></p>
                <img src="https://s2.glbimg.com/CjCye7ok2_y4ZMopRQwGcbZ3aio=/e.glbimg.com/og/ed/f/original/2021/10/08/croissant-frances-1-840x480.jpeg" alt="BOLO VULCÃO">
                <p><b>2 R$:20,00</b></p>
            </div>
        </div>
    </div>