<div class="section" id="contacts">
    <h1><span>CONTATOS</span></h1>
    <div>
        <a href="https://www.instagram.com/thiago_ewer/" target="_blank">
            <img alt="SoloLearn" src="https://www.sololearn.com/Uploads/icons/sololearn.png" />
        </a>
        <a href="#">
            <img alt="Facebook" src="https://www.sololearn.com/Uploads/icons/facebook.png"/>
        </a>
        <a href="#">
            <img alt="Twitter" src="https://www.sololearn.com/Uploads/icons/twitter.png" />
        </a>
    </div>
</div>

<div class="copyright">
    &copy; 2023 thiagoewer@gmail.com All rights reserved.
    
</div>
