<div class="section" id="contacts">
    <h1><span>CONTATOS</span></h1>
    <div>
        <a href="https://www.instagram.com/thiago_ewer/" target="_blank">
            <img alt="Instagram" src="https://www.prg.ufpb.br/arquivocentral/contents/icons/glossy-instagram-icon-png.png/@@images/ddbb1582-286c-4470-bec3-7db141c0393c.png" />
        </a>
        <a href="#">
            <img alt="Facebook" src="https://www.sololearn.com/Uploads/icons/facebook.png"/>
        </a>
        <a href="#">
            <img alt="Twitter" src="https://www.sololearn.com/Uploads/icons/twitter.png" />
        </a>
    </div>
</div>

<div class="copyright">
    &copy; 2023 thiagoewer@gmail.com All rights reserved.
    
</div>
