<div id="header" class="section">
    <img src="https://media.istockphoto.com/id/1094288392/pt/vetorial/man-dollar-necklace.jpg?s=612x612&w=0&k=20&c=ZisB5JH0k-KDavDZ3A_bOSXXuE5kiIWjijjAz9EETro=" class="img-circle">
</div>
<!-- sobre com a classe section -->
<div class="section">
    <h1><span>O CAFETÃO</span></h1>
       <p> 🌟 Desperte seus Sentidos com O Cafetão! 🌟<br>

Bem-vindo ao refúgio do sabor, à sua paixão matinal, ao lugar onde os aromas exalam e os momentos especiais acontecem: <b>O Cafetão!</b><br>
☕ Experiência Inigualável:
Prepare-se para uma jornada sensorial única. Nossos grãos de café selecionados cuidadosamente são torrados para a perfeição, proporcionando uma xícara de café que transcende o comum. Cada gole é uma dança de sabores, uma sinfonia de notas que despertam e inspiram.
🌈 Variedade que Encanta:
No Cafetão, oferecemos uma variedade extensa para agradar a todos os paladares. Desde o expresso robusto até os lattes cremosos, temos a poção mágica para cada amante do café. Não se esqueça de explorar nossas criações exclusivas, cada uma delas feita com amor e paixão.
🛋️ Ambiente Aconchegante:
Imagine-se em um espaço acolhedor, onde a fragrância do café se mistura com risos e conversas. O Cafetão é mais do que uma cafeteria, é um local de encontro, um refúgio para os apreciadores de café que valorizam não apenas a bebida, mas também a atmosfera acolhedora que criamos.  
       </p>
</div>