<div>
        <title>CAFE TÃO</title>
        <link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="style.css">
</div>

<div id="header" class="section">
    <img src="https://media.istockphoto.com/id/1094288392/pt/vetorial/man-dollar-necklace.jpg?s=612x612&w=0&k=20&c=ZisB5JH0k-KDavDZ3A_bOSXXuE5kiIWjijjAz9EETro=" class="img-circle">
</div>
<!--

<div class="menuprinc">
  <a class= "ppadding" href="index.php"> Inicio </a>
  <a class= "ppadding" href="?pg=quemsomos"> Quem somos </a>
  <a class= "ppadding" href="?pg=clientes"> Clientes </a>
  <a class= "ppadding" href="?pg=faleconosco"> Fale Conosco </a>
</div>
-->